site_name: Psalm Documentation
site_url: https://getpsalm.org
repo_url: https://github.com/vimeo/psalm
repo_name: GitHub
site_dir: docs
docs_dir: vendor/vimeo/psalm/docs
theme:
  name: 'mkdocs'
  custom_dir: 'theme_overrides'
extra_css:
  - '../theme_overrides/extra.css'
  - 'https://cloud.typography.com/751592/7707372/css/fonts.css'
nav:
  - Home: README.md
  - Running Psalm:
    - Installation: installation.md
    - Configuration: configuration.md
    - Plugins: plugins.md
    - Command line usage: running_psalm.md
    - IDE support: language_server.md
    - Handling errors:
      - Dealing with code issues: dealing_with_code_issues.md
      - Issue Types: issues.md
    - Checking non-PHP files: checking_non_php_files.md
  - Annotating code:
    - Typing in Psalm: typing_in_psalm.md
    - Docblock Type Syntax: docblock_type_syntax.md
    - Supported Annotations: supported_annotations.md
    - Template Annotations: templated_annotations.md
  - Fixing code: fixing_code.md
