site_name: Psalm Documentation
site_url: https://psalm.dev/docs
repo_url: https://github.com/vimeo/psalm
repo_name: GitHub
site_dir: docs
docs_dir: vendor/vimeo/psalm/docs
theme:
  name: 'mkdocs'
  custom_dir: 'theme_overrides'
extra_css:
  - '../theme_overrides/extra.css'
  - 'https://cloud.typography.com/751592/7707372/css/fonts.css'
nav:
  - Home: README.md
  - Running Psalm:
    - Installation: running_psalm/installation.md
    - Configuration: running_psalm/configuration.md
    - Plugins:
      - Using plugins: running_psalm/plugins/using_plugins.md
      - Authoring plugins: running_psalm/plugins/authoring_plugins.md
      - How Psalm represents types: running_psalm/plugins/plugins_type_system.md
    - Command line usage: running_psalm/command_line_usage.md
    - IDE support: running_psalm/language_server.md
    - Handling errors:
      - Dealing with code issues: running_psalm/dealing_with_code_issues.md
      - Issue Types: running_psalm/issues.md
    - Checking non-PHP files: running_psalm/checking_non_php_files.md
  - Annotating code:
    - Typing in Psalm: annotating_code/typing_in_psalm.md
    - Docblock Type Syntax: annotating_code/docblock_type_syntax.md
    - Supported Annotations: annotating_code/supported_annotations.md
    - Template Annotations: annotating_code/templated_annotations.md
  - Manipulating code:
    - Fixing code with Psalter: manipulating_code/fixing.md
    - Refactoring code: manipulating_code/refactoring.md
